# alpine is lightweight linux version
FROM python:latest

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

# flask default dev port is 5000 so no need tospecifiy and host 0.0.0.0 is the docker network
CMD ["flask", "run", "--host=0.0.0.0"]
